{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-29T07:19:19Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade deps
    sha: 0dd143fed7921e926551b8a0edc79da21b96756c
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: allow the log service to be configured

      via env vars
    sha: 211063a6bcbbaa5fa5d84c002b6f6e016dbbc5dd
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: allow the log service to be configured

      via env vars
    sha: a926d76f1debd6091e49e222b32e0d6fbfdb9f42
  gitHttpUrl: https://github.com/jenkins-x/lighthouse
  gitOwner: jenkins-x
  gitRepository: lighthouse
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/jenkins-x/lighthouse/releases/tag/v1.0.32
  version: 1.0.32
status: {}
 
{{- end }}
