{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-05-19T09:52:36Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: cameron@drivenow.com.au
      name: Cameron Braid
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: fix typo by renaming uses-ussue-1234 to uses-issue-1234
    sha: 42c0c10b07d6adf59f9954f76586582ad3055c47
  gitHttpUrl: https://github.com/jenkins-x/lighthouse
  gitOwner: jenkins-x
  gitRepository: lighthouse
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/jenkins-x/lighthouse/releases/tag/v1.0.42
  version: 1.0.42
status: {}
 
{{- end }}
