{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-30T14:44:55Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore(deps): upgrade jenkins-x/lighthouse to version 1.8.0

      from: https://github.com/jenkins-x/go-scm.git
    sha: ac9e7af661a595f306af8ee9645029e933390a7b
  gitHttpUrl: https://github.com/jenkins-x/lighthouse
  gitOwner: jenkins-x
  gitRepository: lighthouse
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/jenkins-x/lighthouse/releases/tag/v1.0.35
  version: 1.0.35
status: {}
 
{{- end }}
