{{- $apiAll := .Capabilities.APIVersions | toStrings -}}
{{- $ingStableVersion := 19 | int -}}

{{- if .Values.webhooks.ingress.enabled }}
{{- if ge ($.Capabilities.KubeVersion.Minor | int) $ingStableVersion }}
apiVersion: networking.k8s.io/v1
{{- else if has "networking.k8s.io/v1beta1" $apiAll }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "webhooks.name" . }}
  labels:
    app: {{ template "webhooks.name" . }}
  annotations:
    {{- toYaml .Values.webhooks.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.webhooks.ingress.ingressClassName }}
  ingressClassName: {{ .Values.webhooks.ingress.ingressClassName }}
  {{- end }}
  rules:
  {{- range .Values.webhooks.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
        - backend:
        {{- if ge ($.Capabilities.KubeVersion.Minor | int) $ingStableVersion }}
            service:
              name: {{ default (include "webhooks.name" $) $.Values.webhooks.serviceName }}
              port:
                number: {{ $.Values.webhooks.service.externalPort }}
          path: /
          pathType: ImplementationSpecific
        {{- else }}
            serviceName: {{ default (include "webhooks.name" $) $.Values.webhooks.serviceName }}
            servicePort: {{ $.Values.webhooks.service.externalPort }}
        {{- end }}
  {{- end }}
{{- end }}